### ISSUE TITLE
Recommendation for model parameters for mixed and large organic datasets

### ISSUE THREAD

**Issue by chenruduan** [BingqingCheng/cace#7]
Hi Bingqing,

Thanks for your nice work and contribution! I am interested in training CACE on a large organic dataset with 10M structures of energy and forces (Transition1x, https://www.nature.com/articles/s41597-022-01870-w). I borrowed a set similar to the hea setup (see below) but it performed suboptimal. Do you have recommendations on tuning the parameters? Thanks

Best,
Chenru

```
model_config = dict(
    cutoff = 5.,
    cutoff_fn_p = 5,
    n_rbf = 12,
    trainable_rbf = True,
    zs = [1, 6, 7, 8],
    n_atom_basis = 4,
    embed_receiver_nodes = True,
    n_radial_basis = 12,
    max_l = 4,
    max_nu = 3,
    num_message_passing = 1,
    n_layers = 3,
    output_key = 'energy',
    n_hidden = [128, 128],
    residual = False,
    use_batchnorm = False,
    add_linear_nn = True,
)
```

**Comment by BingqingCheng** [comment]
Hi. 

These parameters seem reasonable to me.

In general, I found it to be useful to:
1. first phase of training using very large force loss, and then start a second phase of training with larger energy loss.
2. Somehow restart the training during the first phase helps a lot. See the examples in the cace-fit repo.

**Comment by chenruduan** [comment]
Thanks. This is very helpful
