### ISSUE TITLE
Dataset clarrification

### ISSUE THREAD

**Issue by rfhari** [BingqingCheng/cace#8]
Hi @BingqingCheng, thanks for the wonderful work! 

I also came across [this](https://arxiv.org/abs/2408.15165v1) paper of ewald summation based long range GNN prediction. This seems really interesting! I'm planning to replicate the binding curves of dimers in Fig1. Can you please let me know what are the corresponding dimer IDs you used for generating these curves. There seem to be multiple such dimers for each of the dimer types. 

Thanks!

**Comment by BingqingCheng** [comment]
These are the IDs I used:
sys_list = {
"CC": 0,
"CP": 4,
"PP": 5,
"CA": 2,
"PA": 3,
"AA": 6,
}

**Comment by rfhari** [comment]
Thanks! This is really helpful
